{{- if ( and .Values.mimir.enabled .Values.mimir.datasource.enabled) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mimir-datasource
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
    grafana_datasource: "1"
data:
  tempo-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Mimir
      type: prometheus
      access: proxy
      url: http://{{ .Release.Name }}-mimir-nginx/prometheus
      uid: {{ .Values.mimir.datasource.uid }}
      isDefault: {{ .Values.mimir.datasource.isDefault }}
      {{- with .Values.mimir.datasource.jsonData }}
      jsonData:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
{{- end }}