{{- if and .Values.tempo.enabled .Values.tempo.datasource.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-tempo-datasource
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
    grafana_datasource: "1"
data:
  tempo-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Tempo
      type: tempo
      access: proxy
      url: http://{{ .Release.Name }}-tempo:3100
      uid: {{ .Values.tempo.datasource.uid }}
      isDefault: {{ .Values.tempo.datasource.isDefault }}
      {{- with .Values.tempo.datasource.jsonData }}
      jsonData:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
{{- end }}
